/**
 * phase8/bootstrap.ts
 *
 * Dependency wiring for Phase 8. Assumes Milestone 1/2 repository and pipeline
 * implementations already exist at the paths the roadmap specifies (Steps 1-10)
 * and are NOT regenerated here — only imported and wired.
 *
 * Dependency graph (bottom-up construction order; matches roadmap "Dependency
 * Graph" section exactly — nothing reordered):
 *
 *   Repositories (Step 4)
 *     ITrainingRunRepository, IModelVersionRepository, IRegimePriorRepository,
 *     IStrategyPerformanceRepository, IIndicatorPerformanceRepository,
 *     IRegimePerformanceRepository
 *         │
 *         ▼
 *   Pipeline services (Steps 5-10)
 *     LearningRecordIngester, FeaturePipeline, OutcomeLabeller,
 *     PerformanceAggregator, IndicatorPerformanceCalculator, ModelTrainer
 *         │
 *         ▼
 *   Milestone 3/4 services (Steps 11-14)
 *     ModelRegistry(IModelVersionRepository)
 *     RegimePriorUpdater(IRegimePriorRepository, logger)
 *     ModelArtifactLoader(IModelVersionRepository, logger)
 *     InjectionOrchestrator(ModelRegistry, ModelArtifactLoader, ISystemStateReader, logger)
 *         │
 *         ▼
 *   LearningEngine facade (Step 15)
 *     — depends on every one of the above —
 *         │
 *         ▼
 *   Scheduler wiring (Step 16)
 *     EodTrainingJob(LearningEngine, logger)
 *     PreMarketInjectionJob(LearningEngine, logger)
 *     Phase8StartupCheck(ITrainingRunRepository, PreMarketInjectionJob, logger)
 *     RuntimeScheduler(EodTrainingJob, PreMarketInjectionJob, Phase8StartupCheck, ...)
 */
import { LearningEngine } from './LearningEngine';
import { ModelRegistry } from './services/ModelRegistry';
import { RegimePriorUpdater } from './services/RegimePriorUpdater';
import { ModelArtifactLoader } from './services/ModelArtifactLoader';
import { InjectionOrchestrator } from './services/InjectionOrchestrator';
import { EodTrainingJob } from './scheduler/EodTrainingJob';
import { PreMarketInjectionJob } from './scheduler/PreMarketInjectionJob';
import { Phase8StartupCheck } from './scheduler/Phase8StartupCheck';
import { RuntimeScheduler, type Phase5Refs } from './scheduler/RuntimeScheduler';
import type { ISystemStateReader } from './services/ISystemStateReader';

// --- Milestone 1/2 imports — assumed to exist; not regenerated by this module ---
import type { ITrainingRunRepository } from './repositories/ITrainingRunRepository';
import type { IModelVersionRepository } from './repositories/IModelVersionRepository';
import type { IRegimePriorRepository } from './repositories/IRegimePriorRepository';
import type {IStrategyPerformanceRepository } from './repositories/IStrategyPerformanceRepository';
import type { IIndicatorPerformanceRepository } from './repositories/IIndicatorPerformanceRepository';
import type { IRegimePerformanceRepository } from './repositories/IRegimePerformanceRepository';
import type { ILearningRecordIngester } from './contracts/ILearningRecordIngester';
import type { IFeaturePipeline } from './contracts/IFeaturePipeline';
import type { IOutcomeLabeller } from './contracts/IOutcomeLabeller';
import type { IPerformanceAggregator } from './contracts/IPerformanceAggregator';
import type { IIndicatorPerformanceCalculator } from './contracts/IIndicatorPerformanceCalculator';
import type { IModelTrainer } from './contracts/IModelTrainer';

interface Logger {
  info(msg: string, meta?: Record<string, unknown>): void;
  warn(msg: string, meta?: Record<string, unknown>): void;
  error(msg: string, meta?: Record<string, unknown>): void;
}

export interface Phase8Dependencies {
  trainingRunRepo: ITrainingRunRepository;
  modelVersionRepo: IModelVersionRepository;
  regimePriorRepo: IRegimePriorRepository;
  strategyPerfRepo: IStrategyPerformanceRepository;
  indicatorPerfRepo: IIndicatorPerformanceRepository;
  regimePerformanceRepo: IRegimePerformanceRepository;
  ingester: ILearningRecordIngester;
  featurePipeline: IFeaturePipeline;
  outcomeLabeller: IOutcomeLabeller;
  performanceAggregator: IPerformanceAggregator;
  indicatorPerfCalculator: IIndicatorPerformanceCalculator;
  modelTrainer: IModelTrainer;
  systemStateReader: ISystemStateReader;
  logger: Logger;
}

export interface Phase8RuntimeGraph {
  learningEngine: LearningEngine;
  scheduler: RuntimeScheduler;
}

/**
 * Builds the full Phase 8 object graph. Called once at system bootstrap,
 * after Milestone 1/2 repositories and pipeline services are constructed
 * (this function takes them as inputs — it does not construct them).
 */
export function wirePhase8(
  deps: Phase8Dependencies,
  strategyRunIds: string[],
  phase5Refs: Map<string, Phase5Refs>
): Phase8RuntimeGraph {
  // Milestone 3
  const modelRegistry = new ModelRegistry(deps.modelVersionRepo);
  const regimePriorUpdater = new RegimePriorUpdater(deps.regimePriorRepo, deps.logger);

  // Milestone 4 (injection path)
  const modelArtifactLoader = new ModelArtifactLoader(deps.modelVersionRepo, deps.logger);
  const injectionOrchestrator = new InjectionOrchestrator(
    modelRegistry,
    modelArtifactLoader,
    deps.systemStateReader,
    deps.logger
  );

  // Facade
  const learningEngine = new LearningEngine(
    deps.trainingRunRepo,
    deps.ingester,
    deps.featurePipeline,
    deps.outcomeLabeller,
    deps.performanceAggregator,
    deps.indicatorPerfCalculator,
    deps.strategyPerfRepo,
    deps.indicatorPerfRepo,
    regimePriorUpdater,
    deps.regimePerformanceRepo,
    deps.modelTrainer,
    modelRegistry,
    injectionOrchestrator,
    deps.logger
  );

  // Scheduler wiring
  const eodJob = new EodTrainingJob(learningEngine, deps.logger);
  const injectionJob = new PreMarketInjectionJob(learningEngine, deps.logger);
  const startupCheck = new Phase8StartupCheck(deps.trainingRunRepo, injectionJob, deps.logger);
  const scheduler = new RuntimeScheduler(
    eodJob,
    injectionJob,
    startupCheck,
    strategyRunIds,
    phase5Refs,
    deps.logger
  );

  return { learningEngine, scheduler };
}
